name: "Test"

on: [push]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --aarch64 \
            --target . \
            --docker-hub ghcr.io/mikeomat/ha-actual-budget-sync
